spring:
#  jpa:
#    database: MYSQL
#    hibernate:
#      ddl-auto: create-drop
#      database-platform: org.hibernate.dialect.MySQL55DBDialect
  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true

ribbon:
  IsSecure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
